# Generated by Django 2.2.6 on 2019-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
                ('github_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
