# Generated by Django 2.2.6 on 2019-10-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20191017_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.FloatField(),
        ),
    ]
