# Generated by Django 2.2.6 on 2019-10-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20191017_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
